spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 2
      max-active: 30
      min-idle: 2
      max-wait: 1234
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
#mybatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.uv.entity
#showSql
logging:
  level:
    com:
      uv:
        mapper : debug